### ISSUE TITLE
High server load messages / low CPU utilization

### ISSUE THREAD

**Issue by LuxKeiwoker** [mornedhels/enshrouded-server#113]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Used image version

latest - 1d77460 

### Used docker compose file or docker command

```
services:
  enshrouded:
    image: mornedhels/enshrouded-server:latest
    container_name: enshrouded
    hostname: enshrouded
    restart: unless-stopped
    stop_grace_period: 90s
    ports:
      - "15637:15637/udp"
    volumes:
      - ./game:/opt/enshrouded
    environment:
      - SERVER_NAME=Enshrouded Server
      - SERVER_PASSWORD=secret
      - UPDATE_CRON=*/30 * * * *
      - PUID=4711
      - PGID=4711
```

### What you expected to see, versus what you actually saw

I'm running this container on a Synology NAS with AMD Ryzen CPU and 6 Cores/12 Threads. As soon as more than one player is connected, the game starts complaining about high server load or even excessive load. While looking into the CPU utilization of the container I see only a utilization of up to 300 %, i.e 3 cores or threads. 

The Synology Resource Manager (kind of a taskmanager like in Windows) shows a Cpu utilization of only around 20 %. I've tried many things like redeploying the container, turning on resource restriction, turning it off. Setting the priority of the container to high and even started messing with the docker -cpushares parameter through ssh. Nothing has ever increase CPU utilization. 

At this point I suspect somethings off with the container, rather than the host machine or configuration. 

Any ideas?

**Comment by Zaarrg** [comment]
+1 Got exactly the same issue. With only 2 players got rubber banding and the high server load message in game. Server has more then enough resources with a i5 13500, 20 threads and 64gb. Meanwhile the enshrouded server used max 2gb ram with a max load of 300% aswell. 
No idea if its a docker image issue or enshrouded as i found also a recent reddit post with the same issue.

**Comment by cp-fabian-pittroff** [comment]
Hey there, well I'm experience the same on my setup. I mostly get messages but the game is still playable with 4. In Discord I see also some complains about the performance even on windows servers.

So unfortunately I can't do anything but wait for fixes from the core enshrouded server. A native linux server would also help, so I can get rid of the wine virtualization.

For now you can only try out the `stable-wine` version aswell. Some reported it worked better on their setup.

**Comment by LuxKeiwoker** [comment]
> For now you can only try out the `stable-wine` version aswell. Some reported it worked better on their setup.

Can this use the already existing data folder and savegame for the wine version, or do I need to migrate the savegame to a new data folder?

**Comment by cp-fabian-pittroff** [comment]
> Can this use the already existing data folder and savegame for the wine version, or do I need to migrate the savegame to a new data folder?

You can use the same setup, just switch to the other docker tag and start it back up. If you run into problems, you would migrate the savegames or use one of the backup zip files.

I never played around with the `CPU_TOPOLOGY` env vars, but enshrouded is spawning a lot of threads, so I don't think that would be a problem in that case. It seems that you need a cpu with a high single core performance, so the main thread can keep up.

If you want to play around with the proton or wine env vars, just slap them on your docker compose or docker command and start/restart you docker container. The env variable is passed to the start script and gets picked up by proton/enshrouded.

```yaml
services:
  enshrouded:
    ...
    environment:
      ...
      - PROTON_CPU_TOPOLOGY=4
```

PROTON_CPU_TOPOLOGY=6
```
supervisord: enshrouded-server DEBUG - [72] - PROTON_CPU_TOPOLOGY: 6
...
supervisord: enshrouded-server     Type:      AMD
supervisord: enshrouded-server     Cpus:      6
supervisord: enshrouded-server         Perf:  6 111111
```
PROTON_CPU_TOPOLOGY: 4
```
supervisord: enshrouded-server DEBUG - [72] - PROTON_CPU_TOPOLOGY: 4
...
supervisord: enshrouded-server     Type:      AMD
supervisord: enshrouded-server     Cpus:      4
supervisord: enshrouded-server         Perf:  4 1111
```

And don't be surprised, the debug log is not available in the current builds.
