### ISSUE TITLE
This server is full or unavailable | enshrouded-server [online] Session failed for peer #0 with error 4.

### ISSUE THREAD

**Issue by jzt308** [mornedhels/enshrouded-server#125]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Used image version

1.4.1

### Used docker compose file or docker command

```yaml
services:
  enshrouded:
    image: mornedhels/enshrouded-server:1.4.1
    container_name: enshrouded
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    stop_grace_period: 90s
    volumes:
      - ./volumes/data:/opt/enshrouded
    ports:
      - 15637:15637/udp
    environment:
      - SERVER_NAME=Enshrouded
      - SERVER_IP=0.0.0.0
      - SERVER_SLOT_COUNT=6
      - SERVER_SLOTS=6
      - UPDATE_CRON=*/30 * * * *
      - BACKUP_CRON=* */6 * * *
      - BACKUP_MAX_COUNT=5
      - SERVER_ROLE_1_NAME=Admin
      - SERVER_ROLE_1_PASSWORD=SOMEPASS
      - SERVER_ROLE_1_CAN_KICK_BAN=true
      - SERVER_ROLE_1_CAN_ACCESS_INVENTORIES=true
      - SERVER_ROLE_1_CAN_EDIT_BASE=true
      - SERVER_ROLE_1_CAN_EXTEND_BASE=true
      - SERVER_ROLE_1_RESERVED_SLOTS=1
      - SERVER_ROLE_2_NAME=Friend
      - SERVER_ROLE_2_PASSWORD=SOMEOTHERPASS
      - SERVER_ROLE_2_CAN_KICK_BAN=false
      - SERVER_ROLE_2_CAN_ACCESS_INVENTORIES=true
      - SERVER_ROLE_2_CAN_EDIT_BASE=true
      - SERVER_ROLE_2_CAN_EXTEND_BASE=true
      - SERVER_ROLE_2_RESERVED_SLOTS=3
      - SERVER_ROLE_3_NAME=Guest
      - SERVER_ROLE_3_PASSWORD=THEBESTOTHERPASS
      - SERVER_ROLE_3_CAN_KICK_BAN=false
      - SERVER_ROLE_3_CAN_ACCESS_INVENTORIES=false
      - SERVER_ROLE_3_CAN_EDIT_BASE=false
      - SERVER_ROLE_3_CAN_EXTEND_BASE=false
      - SERVER_ROLE_3_RESERVED_SLOTS=0
    logging:
      driver: loki
      options:
        loki-url: "https://LOKIENDPOINT/loki/api/v1/push"
        loki-external-labels: job=dockerlogs
```

### What you expected to see, versus what you actually saw

I added my server to my steam servers and am able to see it in game as my favorite.
![afbeelding](https://github.com/user-attachments/assets/c919197d-dbff-462c-91f7-48868c71ce69)

I also am able to connect and get prompted for a password of the option to access without password (The Guest Role). 
![afbeelding](https://github.com/user-attachments/assets/3a3f4503-392a-43da-bf90-44ffeba9854b)

On the client I get a loading screen
![afbeelding](https://github.com/user-attachments/assets/0267b9a3-d49a-4deb-9110-e68726f340f3)

And after a little while:
![afbeelding](https://github.com/user-attachments/assets/9e76a93e-d482-441f-a032-822424ce3747)

I would expect to be loaded into the game and connect to the server but this is not the case.

This is on all combinations: so new character/old character; no password; friend password; admin password it doesn't matter. The result is always the same.
The server logs are added below.

I searched on the internet and found several postings (mainly steam) describing the same error and tried some solutions. Using a new character, binding the server to the host machine (docker) or changing the server_ip var inside the compose file either to the actual server ip of the localhost (127.0.0.1) address non worked.

Also I double checked the docker and host logs and my firewall to see if connections are being blocked (not the case as far as I can see). Only some warnings (rsyslogd: warning: ~ action is deprecated, consider using the 'stop' statement instead [v8.2312.0 try https://www.rsyslog.com/e/2307) unrelated to my issue.

Just FYI I also run valheim and satisfactory servers (and redm) on this machine without any issues.

### Logs from the container

```shell
enshrouded  | 2024-12-23 21:17:44.398 supervisord: enshrouded-server ---------------------------------------
enshrouded  | 2024-12-23 21:17:47.372 supervisord: enshrouded-server [online] Session accepted with peer ( id 76561198141176845 ).
enshrouded  | 2024-12-23 21:17:47.372 supervisord: enshrouded-server [online] Added Peer #0.
enshrouded  | 2024-12-23 21:17:50.120 supervisord: enshrouded-server STEAMPS3 - AsyncTCPSocket created
enshrouded  | 2024-12-23 21:18:02.344 supervisord: enshrouded-server [online] Session failed for peer #0 with error 4.
enshrouded  | 2024-12-23 21:18:02.345 supervisord: enshrouded-server STEAMPS3 - AsncTCPSocket destroyed
enshrouded  | 2024-12-23 21:18:02.346 supervisord: enshrouded-server [online] Removed Peer #0.
enshrouded  | 2024-12-23 21:18:14.404 supervisord: enshrouded-server -------------- Session ----------------
```
