### ISSUE TITLE
Add e.g. Discord notification on autoupdate

### ISSUE THREAD

**Issue by FlickyFlack** [mornedhels/enshrouded-server#15]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

I'd really like some kind of notification to an external service like discord when supervisord has detected/installed an update to the gameserver.

Using the following vars added / modified to the compose file:
| Variable              | Default             | Contraints           | Description                                                                                                                  | 
|-----------------------|---------------------|----------------------|------------------------------------------------------------------------------------------------------------------------------|
| `SERVER_NAME`         |           `Enshrouded Server` | string               | The name of the server and the Discord Notification Bot (if enabled)                                                                                                      |  ️  |
| `AVATAR_URL`     |                               | string               | The Profile Picture of the Discord Bot that sends update notifications                                                                                                |     |
| `notifyURL`   |                           | string       | Discord Webhook Link. Documentation can be found [here](https://support.discord.com/hc/en-us/articles/228383668-Intro-to-Webhooks)                                                                                               |     |

A simple push using curl could look like this:
```
curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "{\"username\": \"$(SERVER_NAME)\", \"avatar_url\": \"$(AVATAR_URL)\", \"content\": \"${MESSAGE}\"}" ${notifyURL}
```

While $(MESSAGE) is the literal string that is beeing pushed using the discord webhook.

**Comment by FlickyFlack** [comment]
To add to this, the curl could be used for various logs beeing pushed to the discord webhook, e.g. the player join/leave notification that is beeing read from the service logs

**Comment by cp-fabian-pittroff** [comment]
Hey, I will look into it. But I probably wont add so specific usecases. I could however expose a environment variable to hook into an update event. So you could execute some logic before and or after it triggered (e.g. sending the discord webhook).

The other one with player join/leave is more complicated. For those usecases, it will probably be better, to manage those events outside of the container.

**Comment by cp-fabian-pittroff** [comment]
Hey, I'm preparing a new develop build with initially two hooks. So if you wanna try it out, it is available in both dev images.

| Variable           | Description                            | WIP |
|--------------------|----------------------------------------|:---:|
| `BOOTSTRAP_HOOK`   | Command to run after generel bootstrap | ⚠️  |
| `UPDATE_POST_HOOK` | Command to run after update            | ⚠️  |

For your Discord webhook you can just use the `UPDATE_POST_HOOK`. Curl is already installed in that image.

**Comment by cp-fabian-pittroff** [comment]
Hey @FlickyFlack, this feature is available in the latest `dev` and `dev-proton` image. Could you check if you can run your webhooks with that?

**Comment by FlickyFlack** [comment]
@cp-fabian-pittroff I'll check it out later today, thanks for the implementation!

**Comment by FlickyFlack** [comment]
I've unexpectedly got some time so I got around to testing:
Its not possible to use the full curl command in the compose file, so I got around by attaching a new "scripts" volume that contains the necessary start/update/stop.sh files.

Everything is working as expected! Nice work!

This is my current compose.yaml:
```
version: "3"
services:
  enshrouded:
    image: mornedhels/enshrouded-server:dev
    container_name: enshrouded
    hostname: enshrouded
    restart: unless-stopped
    stop_grace_period: 90s
    ports:
      - "15636-15637:15636-15637/udp"
    volumes:
      - ./game:/opt/enshrouded
      - ./scripts:/opt/scripts
    environment:
      - SERVER_NAME=<Redacted>
      - SERVER_PASSWORD=<Redacted>
      - UPDATE_CRON=*/30 * * * *
      - PUID=4711
      - PGID=4711
      - BOOTSTRAP_HOOK=/opt/scripts/boot.sh
      - UPDATE_POST_HOOK=/opt/scripts/update.sh
      - STEAM_API_KEY=<Redacted>
      - STEAM_API_PUBLIC_IP=<Redacted>
```
A sample boot.sh that includes the current version:
```
#!/bin/bash

SERVER_NAME=<Redacted>
AVATAR_URL='https://img.tapimg.net/market/images/FgKPi--ILo6TZ0nSZlQoULiJH03l.png/appicon'
MESSAGE="The Enshrouded Server has been started with version"
NOTIFY_URL=<Redacted>
CURRENT_VERSION=$(cat /opt/enshrouded/current_version)
MESSAGE="${MESSAGE} ${CURRENT_VERSION}"

curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "{\"username\":\"${SERVER_NAME}\",\"avatar_url\":\"${AVATAR_URL}\",\"content\":\"${MESSAGE}\"}" ${NOTIFY_URL}

```
