### ISSUE TITLE
Server is starting 

### ISSUE THREAD

**Issue by LvInSaNevL** [mornedhels/enshrouded-server#26]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Used image version

(latest) 679be21256f4d4599d1172abd638e320601fa9485991486db9f5fb9a54f9e787

### Used docker compose file or docker command

Here is my docker file

```yml
version: "3"
services:
  enshrouded:
    image: mornedhels/enshrouded-server:latest
    container_name: test_server
    hostname: test_server
    restart: unless-stopped
    stop_grace_period: 90s
    ports:
      - 15636:15636/udp
      - 15637:15637/udp
    volumes:
       - ./save_data:/opt/enshrouded
    environment:
       - SERVER_NAME=Test Server
       - SERVER_PASSWORD=Atestpassword
       - UPDATE_CRON=*/30 * * * *
       - PUID=4711
       - PGID=4711
```

And then I am just starting it with a simple `docker compose up -d`

### What you expected to see, versus what you actually saw

The server starts correctly and I can join the server, but I copied the saved data over from my computer to the server because I was hosting it for a few days, but whenever I join the server is reset back to no progress, like it is a brand new server. 

Looking through `save_data/server/logs/enshrouded_server.log` I see some relevant errors, so I have included them below. 

- When a client connects to the server there is a bunch of messages about successfully connecting and then a single line that looks like an error, `[session] Unable to find machine for peer 0`
- After the `[ecss] Send BuildingZones` message there is about a dozen messages saying `[ecss] Could not add component %hash% for entity 1367` and then about a dozen messages saying `[ecss] Could not remove component %hash% for entity 1367`
- `[savexxx] SAVE 0 bases 0 entities size 1,719`

As I said, the container itself seems to be working fine I am just unable to load my existing save data. 

### Logs from the container

This is the same as what I was seeing in the log file except it also had information about updating the server which all succeded. I can get a copy of it but it would be kind of annoying so I was hoping you wouldn't actually need it haha
