### ISSUE TITLE
Can't find server in steam or in game

### ISSUE THREAD

**Issue by KIRA009** [mornedhels/enshrouded-server#48]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Used image version

mornedhels/enshrouded-server:latest

### Used docker compose file or docker command

```
services:
  enshrouded:
    image: mornedhels/enshrouded-server:latest
    container_name: enshrouded
    hostname: enshrouded
    restart: unless-stopped
    stop_grace_period: 90s
    ports:
      - "15636-15637:15636-15637/udp"
    volumes:
      - ./game:/opt/enshrouded
    environment:
      - SERVER_NAME=servername
      - SERVER_PASSWORD=password
      - PUID=4711
      - PGID=4711
      - UPDATE_CRON=*/30 * * * *
      - log_level=50
```

### What you expected to see, versus what you actually saw

I have added the tail end of the logs. `HostOnline' (up)` tells me that the server is running (as I have already seen from similar issues), but I can't seem to find it in the steam game server or the enshrouded in game search.

I am running the server on ubuntu 22.04, and trying to connect from a windows 10 machine

### Logs from the container

```
enshrouded  | 2024-04-06 08:44:37.499 supervisord: enshrouded-server [online] Server connected to Steam successfully
enshrouded  | 2024-04-06 08:44:37.811 supervisord: enshrouded-server [online] Server is not VAC Secure!
enshrouded  | 2024-04-06 08:44:37.812 supervisord: enshrouded-server [online] Server SteamId: ****
enshrouded  | 2024-04-06 08:44:37.812 supervisord: enshrouded-server [online] Public ipv4: a.b.c.d
enshrouded  | 2024-04-06 08:44:37.812 supervisord: enshrouded-server [OnlineProviderSteam] 'Initialize' (up)!
enshrouded  | 2024-04-06 08:44:37.813 supervisord: enshrouded-server [OnlineProviderSteam] 'JoinOrCreateGame' (up)!
enshrouded  | 2024-04-06 08:44:37.813 supervisord: enshrouded-server [OnlineProviderSteam] 'SetLobbyData' (up)!
enshrouded  | 2024-04-06 08:44:37.813 supervisord: enshrouded-server [OnlineProviderSteam] 'JoinLocalPlayers' (up)!
enshrouded  | 2024-04-06 08:44:37.814 supervisord: enshrouded-server [OnlineProviderSteam] 'ConnectToPeers' (up)!
enshrouded  | 2024-04-06 08:44:37.814 supervisord: enshrouded-server [OnlineProviderSteam] finished transition from 'Uninitialized' to 'InGame' (current='InGame')!
enshrouded  | 2024-04-06 08:44:37.816 supervisord: enshrouded-server [Session] 'HostOnline' (up)!
enshrouded  | 2024-04-06 08:44:37.816 supervisord: enshrouded-server [Session] finished transition from 'Lobby' to 'Host_Online' (current='Host_Online')!
enshrouded  | 2024-04-06 08:44:38.616 supervisord: enshrouded-server [server] Load deserialization took 3.32 s
enshrouded  | 2024-04-06 08:44:39,617 INFO success: enshrouded-server entered RUNNING state, process has stayed up for > than 10 seconds (startsecs)
enshrouded  | 2024-04-06 08:44:39.620 supervisord: enshrouded-updater enshrouded-server: started
enshrouded  | 2024-04-06 08:44:39.664 supervisord: enshrouded-updater INFO - Releasing PID file /var/run/enshrouded/enshrouded-updater.pid
enshrouded  | 2024-04-06 08:44:39.666 supervisord: enshrouded-updater INFO - enshrouded-updater complete
enshrouded  | 2024-04-06 08:44:39,666 INFO exited: enshrouded-updater (exit status 0; expected)
enshrouded  | 2024-04-06 08:49:38.610 supervisord: enshrouded-server [server] Start Saving
enshrouded  | 2024-04-06 08:49:38.622 supervisord: enshrouded-server [savedata] 
enshrouded  | 2024-04-06 08:49:38.623 supervisord: enshrouded-server Compression of Blob 0x00000000::USER took 2.11 ms
enshrouded  | 2024-04-06 08:49:38.623 supervisord: enshrouded-server [savedata] Compression of Blob 0x00000000::KNOW took 26.00 us
```
