### ISSUE TITLE
Question about config folder

### ISSUE THREAD

**Issue by Overactt** [mornedhels/enshrouded-server#57]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Question

Hey, 1st time making a dedicated server with docker and new to docker as well.

I'm trying to figure out where the config file of the server are going ?
Here's my docker compose i used on portainer :

```
version: "3"
services:
  enshrouded:
    image: mornedhels/enshrouded-server:latest
    container_name: enshrouded
    hostname: enshrouded
    restart: unless-stopped
    stop_grace_period: 90s
    ports:
      - "15636-15637:15636-15637/udp"
    volumes:
      - /mnt/server/enshrouded:/mnt/server/enshrouded
    environment:
      - SERVER_NAME=Enshrouded Server
      - SERVER_PASSWORD=secret
      - UPDATE_CRON=*/30 * * * *
      - PUID=4711
      - PGID=4711
```

     

 I got a mountpoint with my ZFS in /mnt, that is why i would have expect to find config here but no, it just create the folder empty. 
![image](https://github.com/mornedhels/enshrouded-server/assets/72161139/703db749-4031-4092-b81e-c4d8f2ac8762)

Server is working fine but i just can't see where the files of the server are

Thanks!
