### ISSUE TITLE
Server_password vs UserGroups password

### ISSUE THREAD

**Issue by OnigamiSama** [mornedhels/enshrouded-server#71]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Question

Hey! I have the same error using the docker-compose example, can confirm that the server_password variable is not written in enshrouded_server.json

I made sure that all files are owned by my user (1000:1000) and the PUID and PGID are correct.

Following what said @Nitrocrusher in #66 I tried to login using the userGroups password (wich is not the same as server_password) and it worked.

Is it supposed to work like this? UserGroups password overriding server_password ?

docker-compose.yml

```
services:
  enshrouded:
    image: mornedhels/enshrouded-server:latest
    container_name: enshrouded_proton
    hostname: enshrouded_proton
    restart: unless-stopped
    stop_grace_period: 90s
    ports:
      - "15637:15637/udp"
    volumes:
      - ./data/config:/opt/enshrouded
    environment:
      - SERVER_NAME=Enshrouded Server
      - SERVER_PASSWORD=MyPassword
      - UPDATE_CRON=*/30 * * * *
      - PUID=1000
      - PGID=1000
```
