### ISSUE TITLE
Save game doesnt exist and server difficulty Env does not work

### ISSUE THREAD

**Issue by jonneymendoza** [mornedhels/enshrouded-server#87]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Used image version

latest/1.30

### Used docker compose file or docker command

Docker compose yml file:

```yaml
services:
  enshrouded:
    image: mornedhels/enshrouded-server:latest
    container_name: enshrouded
    hostname: enshrouded
    restart: unless-stopped
    stop_grace_period: 90s
    ports:
      - "15637:15637/udp"
    volumes:
      - /home/config/enshrouded:/opt/enshrouded
    environment:
      - SERVER_NAME=MyServer
      - UPDATE_CRON=*/30 * * * *
      - BACKUP_CRON=*/10 * * * *
      - SERVER_SAVE_DIR=/home/me/enshrouded/save
      - BACKUP_DIR=/home/me/enshrouded/backup
      - PUID=1000
      - PGID=1000
      - SERVER_ROLE_0_NAME=Admin
      - SERVER_ROLE_0_PASSWORD=myPassword
      - SERVER_ROLE_0_CAN_KICK_BAN=true
      - SERVER_ROLE_0_CAN_ACCESS_INVENTORIES=true
      - SERVER_ROLE_0_CAN_EDIT_BASE=true
      - SERVER_ROLE_0_CAN_EXTEND_BASE=true
      - SERVER_ROLE_0_RESERVED_SLOTS=1
      - SERVER_ROLE_1_NAME=Friends
      - SERVER_ROLE_1_PASSWORD=mates
      - SERVER_ROLE_1_CAN_ACCESS_INVENTORIES=true
      - SERVER_ROLE_1_CAN_EDIT_BASE=true
      - SERVER_ROLE_1_CAN_EXTEND_BASE=true
      - SERVER_ROLE_1_RESERVED_SLOTS=6
      - SERVER_ROLE_2_NAME=Guests
      - SERVER_ROLE_2_PASSWORD=hello
      - SERVER_GS_PRESET=Custom
      - SERVER_GS_PLAYER_HEALTH_FACTOR=2
      - SERVER_GS_PLAYER_MANA_FACTOR=4
      - SERVER_GS_PLAYER_STAMINA_FACTOR=2
      - SERVER_GS_ENABLE_DURABILITY=true
      - SERVER_GS_ENABLE_STARVING_DEBUFF=false
      - SERVER_GS_FOOD_BUFF_DURATION_FACTOR=1
      - SERVER_GS_FROM_HUNGER_TO_STARVING=600000000000
      - SERVER_GS_SHROUD_TIME_FACTOR=1
      - SERVER_GS_RANDOM_SPAWNER_AMOUNT=Normal
      - SERVER_GS_MINING_DAMAGE_FACTOR=2
      - SERVER_GS_PLANT_GROWTH_SPEED_FACTOR=1
      - SERVER_GS_RESOURCE_DROP_STACK_AMOUNT_FACTOR=2
      - SERVER_GS_FACTORY_PRODUCTION_SPEED_FACTOR=2
      - SERVER_GS_PERK_UPGRADE_RECYCLING_FACTOR=0.5
      - SERVER_GS_PERK_COST_FACTOR=1
      - SERVER_GS_EXPERIENCE_COMBAT_FACTOR=1
      - SERVER_GS_EXPERIENCE_MINING_FACTOR=1
      - SERVER_GS_EXPERIENCE_EXPLORATION_QUESTS_FACTOR=1
      - SERVER_GS_AGGRO_POOL_AMOUNT=Normal
      - SERVER_GS_ENEMY_DAMAGE_FACTOR=1
      - SERVER_GS_ENEMY_HEALTH_FACTOR=1
      - SERVER_GS_ENEMY_STAMINA_FACTOR=1
      - SERVER_GS_ENEMY_PERCEPTION_RANGE_FACTOR=1
      - SERVER_GS_BOSS_DAMAGE_FACTOR=1
      - SERVER_GS_BOSS_HEALTH_FACTOR=1
      - SERVER_GS_THREAT_BONUS=1
      - SERVER_GS_PACIFY_ALL_ENEMIES=false
      - SERVER_GS_DAY_TIME_DURATION=1800000000000
      - SERVER_GS_NIGHT_TIME_DURATION=720000000000
      - SERVER_GS_TOMBSTONE_MODE=AddBackpackMaterials
```

Compose command i used: `sudo docker compose -f enshrouded-compose.yml up -d`

This is what the ensoruded_server.json file generates from the given compose yml and command on my ubuntu server

```json
{
  "name": "MyServer",
  "saveDirectory": "/home/me/enshrouded/save",
  "logDirectory": "./logs",
  "ip": "0.0.0.0",
  "queryPort": 15637,
  "slotCount": 16,
  "gameSettingsPreset": "Default",
  "gameSettings": {
    "playerHealthFactor": 1,
    "playerManaFactor": 1,
    "playerStaminaFactor": 1,
    "enableDurability": true,
    "enableStarvingDebuff": false,
    "foodBuffDurationFactor": 1,
    "fromHungerToStarving": 600000000000,
    "shroudTimeFactor": 1,
    "tombstoneMode": "AddBackpackMaterials",
    "miningDamageFactor": 1,
    "plantGrowthSpeedFactor": 1,
    "resourceDropStackAmountFactor": 1,
    "factoryProductionSpeedFactor": 1,
    "perkUpgradeRecyclingFactor": 0.500000,
    "perkCostFactor": 1,
    "experienceCombatFactor": 1,
    "experienceMiningFactor": 1,
    "experienceExplorationQuestsFactor": 1,
    "randomSpawnerAmount": "Normal",
    "aggroPoolAmount": "Normal",
    "enemyDamageFactor": 1,
    "enemyHealthFactor": 1,
    "enemyStaminaFactor": 1,
    "enemyPerceptionRangeFactor": 1,
    "bossDamageFactor": 1,
    "bossHealthFactor": 1,
    "threatBonus": 1,
    "pacifyAllEnemies": false,
    "dayTimeDuration": 1800000000000,
    "nightTimeDuration": 720000000000
  },
  "userGroups": [
    {
      "name": "Admin",
      "password": "mypassword",
      "canKickBan": true,
      "canAccessInventories": true,
      "canEditBase": true,
      "canExtendBase": true,
      "reservedSlots": 1
    },
    {
      "name": "Friends",
      "password": "mates",
      "canKickBan": false,
      "canAccessInventories": true,
      "canEditBase": true,
      "canExtendBase": true,
      "reservedSlots": 6
    },
    {
      "name": "Guests",
      "password": "hello",
      "canKickBan": false,
      "canAccessInventories": false,
      "canEditBase": false,
      "canExtendBase": false,
      "reservedSlots": 0
    }
  ]
}
```

### What you expected to see, versus what you actually saw

Save file to be in: home/me/enshrouded/save
Backup saves to be in /home/me/enshrouded/backup
Server difficulty to be set t Custom with the given settings i had tweaked.

**Comment by cp-fabian-pittroff** [comment]
Hey @jonneymendoza,
thanks for the bug report. The savefiles should be an easy fix. You configured them to `/home/me/enshrouded/save` - but this is inside of the docker container. Enshrouded should handle the creation of the directory, but you would have to add the volumes to get the saves.

```yaml
services:
  enshrouded:
    image: mornedhels/enshrouded-server:latest
    ...
    volumes:
      - /home/config/enshrouded:/opt/enshrouded
      - /host/path/save:/home/me/enshrouded/save
      - /host/path/backup:/home/me/enshrouded/backup
```

But I would stick to the default path. You could also add a different host directory for that explicitly (like `/host/path/save:/opt/enshrouded/savegame`).

For the gamesettings I don't see a clear solution. Would it be possilbe to start the container with debug logs enabled?

```yaml
services:
  enshrouded:
    image: mornedhels/enshrouded-server:latest
    ...
    environment:
      - log_level=50
      - ...
```

Hopefully this will get us more insights, as to why the config is not getting applied correctly.
